### ISSUE TITLE
Import button in Blender not working and GoZ not installing in ZBrush

### ISSUE THREAD

**Issue by ShadowOTC** [JoseConseco/GoB#391]
I installed the add-on in Blender and installed GoZ in the troubleshooting tab.
Then i tried to hit the import button to keep it on and i got this error:
![image](https://user-images.githubusercontent.com/47579857/207867274-4a96caad-267d-49bd-9d53-08cd4740cd7a.png)

Then i opened ZBrush and saw that GoZ didn't installed because Blender wasn't among the options.
The installation path looks correct:
![image](https://user-images.githubusercontent.com/47579857/207868505-77ce97f0-774c-43ee-a536-ef93f664a3e3.png)

I'm trying to install the plugin for a few months now trying all the versions and i'm always getting the same error.
I don't know how to find the problem so if you can help me i would really appreciate it.

ZBrush version: 2022.0.5
Blender version: 3.3.0

**Comment by kromar** [comment]
did you export something from zbrush? im not sure that file will exist unless a mesh has been exported from blender or from zbrush via GoZ. 
Of course the error should not happen so i will have a closer look since i have not seen this before.

What version of GoB are you using?

**Comment by kromar** [comment]
can you navigate to this folder and show me the content of it? C:\Users\Public\Pixologic\GoZBrush\
The error seems to occur because the GoZ_ObjectList.txt is missing from that folder which would indicate that GoZ was not properly installed for zbrush

**Comment by ShadowOTC** [comment]
![image](https://user-images.githubusercontent.com/47579857/207974104-4f314ecf-ddaf-4a7d-9b05-567888e49e82.png)

**Comment by kromar** [comment]
hm i think there are a bunch of things missing but not sure why. You can try this branch, it will create that missing file when you enable the import so maybe that gets you a step further but i would expect there to be more missing files or folders to get it working. We can try to work through it and see if this can eventually be resolved by the blender plugin.

https://github.com/kromar/blender_GoB/tree/create-missing-file  v3_5_97

**Comment by ShadowOTC** [comment]
Still the same error:
![image](https://user-images.githubusercontent.com/47579857/207979597-d98c7676-32bc-4401-a70e-2e0e6d9986a3.png)

And still no GoZ installation. When i click on GoZ, ZBrush asks me to select the application:
![image](https://user-images.githubusercontent.com/47579857/207979727-bfe88985-8367-47f3-a602-98d595f9adc8.png)

**Comment by kromar** [comment]
Oh i forgot to push the changes, please try again, the fix should now be in.

It should not be a issue that zbrush does not find blender since the GoB addon does not rely on Zbrush. Its also not doing it for me so yo can ignore that message and choose "Dont show again" it should still export your meshes.

You could check if these things exist:
1. There should be a entry in this file with the name of your exported mesh: C:\Users\Public\Pixologic\GoZBrush\GoZ_ObjectList.txt 
2. There should be a .GoZ and .ztl file in this folder: C:\Users\Public\Pixologic\GoZProjects\Default

If that exists blender should be able to deal with it and import the files.

**Comment by kromar** [comment]
so what happens now if you export a mesh from zbrush with GoZ? Does the file appear in GoZProjects\Default and the GoZ_ObjectList.txt?

![image](https://user-images.githubusercontent.com/1472884/208104901-4b0e3988-decf-4e1c-ad72-6edc46c98a9d.png)

**Comment by ShadowOTC** [comment]
I can't export because ZBrush is blocking me with the screenshot i sent in the previous message.

**Comment by kromar** [comment]
Ok then there is still something missing, can you try to export a object from blender and see if that fixes the issue? The addon is writing some config files in the goz folder which should configure the blender export on zbrush.
Also make sure that zbrush is closed when exporting from blender.

**Comment by ShadowOTC** [comment]
Okay, so... When i tried to export from Blender to ZBrush it worked and when i tried to click on GoZ, i got this:
![image](https://user-images.githubusercontent.com/47579857/208134405-e10fbf8e-00c0-4c39-98b1-3cd137df9c42.png)
Everything in the GoZ side is working now.

Then i tried to export from ZBrush to Blender. Using the middle button i got this error:
![image](https://user-images.githubusercontent.com/47579857/208134583-79067cf2-0f25-41ad-b98e-f5f20b14e66a.png)
I'm only able to import the model using the right-side button (the one that looks like a download arrow).

**Comment by kromar** [comment]
alright we are almost there, i pushed another fix which should resolve this issue: https://github.com/kromar/blender_GoB/tree/create-missing-file

**Comment by ShadowOTC** [comment]
Everything now is working correctly.
- GoZ Export is working;
- Blender to ZBrush export is working;
- Import button is working;
- Manual Import button is working.

Thank you for everything. 🗿🍷

**Comment by kromar** [comment]
that is fantastic to hear! im glad we got it to work for you! happy blending
